### ISSUE TITLE
同步加载和异步加载有何区别

### ISSUE THREAD

**Issue by vxhly** [ywwhack/babel-plugin-equire#1]
有点不理解同步加载和异步加载，这两的区别是？实际使用过程中，同步加载好还是异步加载好
在提一个问题，官方文档是说 ，`echarts\src\**`  这里的代码体积会相对小一点，那怎么配置，

**Comment by ywwhack** [comment]
@vxhly 
同步加载是指把 echarts 相关的代码都打包到类似 vendor 这样的文件中，在页面第一次加载的时候 echarts 就会被加载完成

异步加载对应的就是 code splitting，只有当你用到 echarts 的时候才会加载 echarts 的代码，这样可以减少首次加载的体积

目前这个库的作用就是动态引入 echarts\src\**，如果感兴趣可以看看源码 :)

**Comment by vxhly** [comment]
明白了


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/ywwhack/babel-plugin-equire","title":"ywwhack/babel-plugin-equire","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/ywwhack/babel-plugin-equire"}},"updates":{"snippets":[{"icon":"PERSON","message":"@ywwhack in #1: 同步加载是指把 echarts 相关的代码都打包到类似 vendor 这样的文件中，在页面第一次加载的时候 echarts 就会被加载完成\r\n\r\n异步加载对应的就是 code splitting，只有当你用到 echarts 的时候才会加载 echarts 的代码，这样可以减少首次加载的体积\r\n\r\n目前这个库并不支持配置 echarts\\src\\**"}],"action":{"name":"View Issue","url":"https://github.com/ywwhack/babel-plugin-equire/issues/1#issuecomment-353916719"}}}
