### ISSUE TITLE
异步加载

### ISSUE THREAD

**Issue by vxhly** [ywwhack/babel-plugin-equire#2]
执行 npm run build 之后，上线，文件并没有被加载
![image](https://user-images.githubusercontent.com/17906558/34359868-7de56e8c-ea96-11e7-9f4a-53921200bd64.png)
![image](https://user-images.githubusercontent.com/17906558/34359879-89822960-ea96-11e7-9f89-118da0bb9a33.png)
![image](https://user-images.githubusercontent.com/17906558/34359885-9806e20a-ea96-11e7-9ff8-903180349779.png)
![image](https://user-images.githubusercontent.com/17906558/34359907-c723b770-ea96-11e7-8094-e8cafbdb7c4f.png)

但是在执行 npm run dev 时，是没有问题的
所以，时我漏了那个步骤

**Comment by ywwhack** [comment]
似乎跟这个有关 https://github.com/JeffreyWay/laravel-mix/issues/164

**Comment by vxhly** [comment]
@ywwhack 这边的确是有需求要改 assetsPublicPath 
```bash
build: {
    // Template for index.html
    index: path.resolve(__dirname, '../dist/index.html'),

    // Paths
    assetsRoot: path.resolve(__dirname, '../dist'),
    assetsSubDirectory: 'static',
    assetsPublicPath: '/app',
}
```
这种情况要怎么解决

**Comment by vxhly** [comment]
知道怎么玩了，assetsPublicPath 配置成 /app, 那么加载的时候会变成   /appstatic/xxx.js，改成 /app/ 则生成URL就不会有问题了
