### ISSUE TITLE
使用js版本主题，按需引入不生效

### ISSUE THREAD

**Issue by Spacesless** [ywwhack/babel-plugin-equire#5]
需求：在按需引入echarts的时候就直接注册主题
问题：直接import js格式的主题，开发环境下按需引入会失效，生产环境打包没影响，可能因为主题文件里面require('echats')
```
import '@/mixins/walden'
const initEcharts = async(element, isTheme = true) => {
  const echarts = await equireCharts()
  return isTheme ? echarts.init(element, 'walden') : echarts.init(element)
}
export default initEcharts
```

临时解决方案：使用JSON格式的主题  (๑•ㅂ•́)و✧
```
import theme from '@/mixins/theme.json'
const initEcharts = async(element, isTheme = true) => {
  const echarts = await equireCharts()
  return isTheme ? (echarts.registerTheme('walden', theme), echarts.init(element, 'walden'))
    : echarts.init(element)
}
export default initEcharts
```

**Comment by 490567134** [comment]
> 需求：在按需引入echarts的时候就直接注册主题
> 问题：直接import js格式的主题，开发环境下按需引入会失效，生产环境打包没影响，可能因为主题文件里面require('echats')
> 
> ```
> import '@/mixins/walden'
> const initEcharts = async(element, isTheme = true) => {
>   const echarts = await equireCharts()
>   return isTheme ? echarts.init(element, 'walden') : echarts.init(element)
> }
> export default initEcharts
> ```
> 
> 临时解决方案：使用JSON格式的主题 (๑•ㅂ•́)و✧
> 
> ```
> import theme from '@/mixins/theme.json'
> const initEcharts = async(element, isTheme = true) => {
>   const echarts = await equireCharts()
>   return isTheme ? (echarts.registerTheme('walden', theme), echarts.init(element, 'walden'))
>     : echarts.init(element)
> }
> export default initEcharts
> ```

你的能自动按需引入模块吗？我自己测试了echarts还是整个包，打包完文件大小一样，没起作用

**Comment by zhixiaotong** [comment]
> > 需求：在按需引入echarts的时候就直接注册主题
> > 问题：直接import js格式的主题，开发环境下按需引入会失效，生产环境打包没影响，可能因为主题文件里面require('echats')
> > ```
> > import '@/mixins/walden'
> > const initEcharts = async(element, isTheme = true) => {
> >   const echarts = await equireCharts()
> >   return isTheme ? echarts.init(element, 'walden') : echarts.init(element)
> > }
> > export default initEcharts
> > ```
> > 
> > 
> > 临时解决方案：使用JSON格式的主题 (๑•ㅂ•́)و✧
> > ```
> > import theme from '@/mixins/theme.json'
> > const initEcharts = async(element, isTheme = true) => {
> >   const echarts = await equireCharts()
> >   return isTheme ? (echarts.registerTheme('walden', theme), echarts.init(element, 'walden'))
> >     : echarts.init(element)
> > }
> > export default initEcharts
> > ```
> 
> 你的能自动按需引入模块吗？我自己测试了echarts还是整个包，打包完文件大小一样，没起作用

我也出现了一样的问题，只引入了line和bar，结果打包全部都在，没有生效。请问你后面解决了么？

**Comment by Spacesless** [comment]
> > > 需求：在按需引入echarts的时候就直接注册主题
> > > 问题：直接import js格式的主题，开发环境下按需引入会失效，生产环境打包没影响，可能因为主题文件里面require('echats')
> > > ```
> > > import '@/mixins/walden'
> > > const initEcharts = async(element, isTheme = true) => {
> > >   const echarts = await equireCharts()
> > >   return isTheme ? echarts.init(element, 'walden') : echarts.init(element)
> > > }
> > > export default initEcharts
> > > ```
> > > 
> > > 
> > > 临时解决方案：使用JSON格式的主题 (๑•ㅂ•́)و✧
> > > ```
> > > import theme from '@/mixins/theme.json'
> > > const initEcharts = async(element, isTheme = true) => {
> > >   const echarts = await equireCharts()
> > >   return isTheme ? (echarts.registerTheme('walden', theme), echarts.init(element, 'walden'))
> > >     : echarts.init(element)
> > > }
> > > export default initEcharts
> > > ```
> > 
> > 
> > 你的能自动按需引入模块吗？我自己测试了echarts还是整个包，打包完文件大小一样，没起作用
> 
> 我也出现了一样的问题，只引入了line和bar，结果打包全部都在，没有生效。请问你后面解决了么？

**Comment by Spacesless** [comment]
> > > 需求：在按需引入echarts的时候就直接注册主题
> > > 问题：直接import js格式的主题，开发环境下按需引入会失效，生产环境打包没影响，可能因为主题文件里面require('echats')
> > > ```
> > > import '@/mixins/walden'
> > > const initEcharts = async(element, isTheme = true) => {
> > >   const echarts = await equireCharts()
> > >   return isTheme ? echarts.init(element, 'walden') : echarts.init(element)
> > > }
> > > export default initEcharts
> > > ```
> > > 
> > > 
> > > 临时解决方案：使用JSON格式的主题 (๑•ㅂ•́)و✧
> > > ```
> > > import theme from '@/mixins/theme.json'
> > > const initEcharts = async(element, isTheme = true) => {
> > >   const echarts = await equireCharts()
> > >   return isTheme ? (echarts.registerTheme('walden', theme), echarts.init(element, 'walden'))
> > >     : echarts.init(element)
> > > }
> > > export default initEcharts
> > > ```
> > 
> > 
> > 你的能自动按需引入模块吗？我自己测试了echarts还是整个包，打包完文件大小一样，没起作用
> 
> 我也出现了一样的问题，只引入了line和bar，结果打包全部都在，没有生效。请问你后面解决了么？

没问题的啊
babel-plugin-equire  1.1.1
babel.config.js：
```
module.exports = {
  presets: [
    '@vue/cli-plugin-babel/preset'
  ],
  'plugins': [
    [
      'component-scss',
      {
        'libraryName': 'element-ui',
        'styleLibraryName': 'theme-chalk/src',
        'ext': '.scss'
      }
    ],
    'equire'
  ]
}
```
equire使用实例
```
// 使用JSON格式registerTheme，js注册方式可能会影响equire按需引入，新版本未验证
import theme from '@/mixins/theme.json'
/**
 * 按需引入Echarts模块
 * @param {Array} 需要引入的模块
 * @see {*} https://github.com/ywwhack/babel-plugin-equire#转化规则
 */
const echarts = equire(['bar', 'line', 'pie', ......]) 

/**
 * 实例化Echarts
 * @param {Nodes} element DOM 容器
 * @param {Boolean} isRegisterTheme 是否注册主题
 * @param {Boolean} isExpose 是否暴露echarts，部分绘图需用到echarts的方法
 * @returns {Object} {echarts: echarts对象, instance: echarts的实例化对象}
 */
const initEcharts = (element, isRegisterTheme = true, isExpose = false) => {
  if (isExpose) {
    return {
      echarts,
      instance: isRegisterTheme ? (echarts.registerTheme('walden', theme), echarts.init(element, 'walden')) : echarts.init(element)
    }
  } else {
    return isRegisterTheme ? (echarts.registerTheme('walden', theme), echarts.init(element, 'walden')) : echarts.init(element)
  }
}

export default initEcharts
```
打包后chunk-echarts只有300多K，图表只包含line、bar、pie

**Comment by zhixiaotong** [comment]
![648a69048995ec5e71fead9bb696984](https://user-images.githubusercontent.com/34681550/93159458-cbf4b100-f740-11ea-9bc6-40ceeeed9390.jpg)
![微信图片_20200915104027](https://user-images.githubusercontent.com/34681550/93158824-85eb1d80-f73f-11ea-857f-c69d4739668e.jpg)
![960f99c331be0079d5666ea81db772f](https://user-images.githubusercontent.com/34681550/93158876-a4511900-f73f-11ea-84e1-5cacce1571ae.jpg)
感谢回复~
babel-plugin-equire版本1.1.1
echarts版本4.2.1
但是我的确存在这个问题。打包后echarts还是有2.33M左右，如图所示，包含了一堆/lib/，但我并没有引入。很苦恼~

**Comment by Spacesless** [comment]
你先不引入主题看看

**Comment by zhixiaotong** [comment]
> 你先不引入主题看看

还是不行，请问你使用的echarts版本是多少？

**Comment by Spacesless** [comment]
> > 你先不引入主题看看
> 
> 还是不行，请问你使用的echarts版本是多少？

4.8.0

**Comment by zhixiaotong** [comment]
> > > 你先不引入主题看看
> > 
> > 
> > 还是不行，请问你使用的echarts版本是多少？
> 
> 4.8.0

谢谢~

**Comment by zhixiaotong** [comment]
> > > 你先不引入主题看看
> > 
> > 
> > 还是不行，请问你使用的echarts版本是多少？
> 
> 4.8.0

我之前解决了这个问题了，这边回复你一下，以表示感谢。首先，echarts按需引入失效，打包依然是全局引入的原因的确是主题影响。主题js文件内部有equire('echarts')，要么把这个改成equire('echarts/lib/echarts')，但这样涉及很多主题js的改动，我在echarts的issue上看到开发者说这么改动，而我这边是vue开发，直接可以在vue.config.js里面添加别名：echarts$: ‘echarts/lib/echarts’，这样可以一次性解决开发环境和生产环境按需引入的问题。希望对你有所帮助~
